name: Test Self-Hosted Runner
     
on:
  push:
    branches:
      - main 
  workflow_dispatch:  

jobs:
  ci-pipeline:
    runs-on: self-hosted

    steps:

      - name: Print Message
        run: echo "Self-hosted runner is working!"

      - name: Set Docker Version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build API
        run: make build-api

      # - name: Run Tests
        # run: make test

      - name: Perform Code Linting
        run: make lint

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 
        

      - name: Docker Build
        run: docker build -t test-sre:v1.1.2 .

      - name: Docker Push
        run: docker push test-sre:v1.1.2